first
devkekops/gophermart pull request #1
Opened 2022-05-27 16:09 UTC by devkekops

2022-06-04 08:15 UTC, Bazys commented
Привет!
Я начал проверять код. 
А пока рекомендую прйтись по нему линтером. 
Например, установи [golangci-lint](https://golangci-lint.run/usage/install/#local-installation), затем запусти проверку  командой ```golangci-lint run --timeout 90s --exclude-use-default```
Стандартные ошибки по типу того, что пропущена проверка на возврат ошибки, можно иправить сходу, как минимум залогировав. 
И первый вопрос который по итогу работы этого линтера, это зачем нужна структура ```Session``` в файле ```auth_middleware.go```, судя повсему она не используется.

2022-06-04 10:32 UTC, Bazys requested changes

2022-06-04 10:32 UTC, Bazys commented on internal/app/storage/repo_db.go
> +	mutex  sync.RWMutex
при работе с БД нет необходимости в mutex.
Мехнизм блокировки реализовывается при помощи транзакций

2022-06-04 10:32 UTC, Bazys commented on internal/app/storage/storage.go
> +type Order struct {
структуры с данными лучше выделять в отдельный пакет `entity`
Пакет `Entity` определяет основные сущности для бизнес-логики (сервисов), сопоставления базы данных и объектов ответа HTTP, если они подходят. Каждая логическая группа объектов в собственном файле.

2022-06-04 10:32 UTC, Bazys commented on cmd/gophermart/main.go
> +	log.Fatal(server.Serve(&cfg))
не стал подключать нормальный логер?
Не забывай что stdlib-ный логер он синхронный и не подходит для больших нагрузок.
Понимаю что в данном проекте их нет, но надо в принципе приучать себя к таким вещам.

2022-06-04 10:32 UTC, Bazys commented on cmd/gophermart/main.go
> +		SecretKey:            "asdhkhk1375jwh132",
`SecretKey` желательно в принципе никак не хардкодить. Если боишься что может случится вариант что не считается ни из `env`, ни из командной строки, генерируй рандомную строку при инициализации приложения.

2022-06-04 10:32 UTC, Bazys commented on internal/app/client/client.go
> +type Client struct {
раз у тебя все поля приватные, в этой структуре, то есть ли смысл в конструкторе возвращать саму структуру? Может описать интерфейс и возвращать его?

2022-06-04 10:32 UTC, Bazys commented on internal/app/client/client.go
> +type Client struct {
```suggestion
type Client interface {
	GetAccrualInfo(number string) (AccrualResponse, error)
}
type cli struct {
```

2022-06-04 10:32 UTC, Bazys commented on internal/app/client/client.go
> +func (c *Client) GetAccrualInfo(number string) (AccrualResponse, error) {
```suggestion
func (c *cli) GetAccrualInfo(number string) (AccrualResponse, error) {
```

2022-06-04 10:32 UTC, Bazys commented on internal/app/client/client.go
> +func NewClient(host string, timeout int) *Client {
```suggestion
func New(host string, timeout int) Client {
```

2022-06-04 10:32 UTC, Bazys commented on internal/app/client/client.go
> +	return &Client{
```suggestion
	return &cli{
```

2022-06-04 10:32 UTC, Bazys commented on internal/app/client/client.go
> +	//fmt.Println(res.StatusCode)
ПР для мержа в мастер не должны содержать такие строчки.

2022-06-04 10:32 UTC, Bazys commented on internal/app/handlers/auth_middleware.go
> +	if len(session) < 33 {
а почему именно 33?
1. Надо выносить в константы
2. А если что-то изменится?

2022-06-04 10:32 UTC, Bazys commented on internal/app/handlers/auth_middleware.go
> +			secretKeyByte := []byte(secretKey)
эта переменная используется только в одном случае.
Может ее там и инициализировать?

2022-06-04 10:32 UTC, Bazys commented on internal/app/handlers/auth_middleware.go
> +				userID, err := checkSignature(cookieValue, secretKeyByte)
```suggestion
				userID, err := checkSignature(cookieValue, []byte(secretKey))
```

2022-06-04 10:32 UTC, Bazys commented on internal/app/handlers/auth_middleware.go
> +					http.Error(w, "Invalid credentials", http.StatusUnauthorized)
`"Invalid credentials"` я бы эти строки вынес в константы.

2022-06-04 10:32 UTC, Bazys commented on internal/app/handlers/basehandler.go
> +	*chi.Mux
`Mux` - реально нужно публичным?

2022-06-04 10:32 UTC, Bazys commented on internal/app/handlers/handlers.go
> +		userID := userIDctx.(string)
рекомендую все таки полную форму type assertion `v, ok := x.(T)` 
мало ли что свалится в контекст

2022-06-04 10:32 UTC, Bazys commented on internal/app/handlers/handlers.go
> +		userIDctx := req.Context().Value(userIDKey)
хоть всего и 2 строчки, но они повторяются в каждом хандлере.
Рекомендую вынести в отдельную функцию

2022-06-04 10:32 UTC, Bazys commented on internal/app/handlers/handlers.go
> +		json.NewEncoder(&buf).Encode(balance)
а чем не устроил вариант с 234 строчки?

2022-06-04 10:32 UTC, Bazys commented on internal/app/server/server.go
> +	repo, err := storage.NewRepoDB(cfg.DatabaseURI, client)
Если переписать на интерфейсы, то смена клиента не повлияет на код здесь.

2022-06-04 10:32 UTC, Bazys commented on internal/app/storage/repo_db.go
> +					w.repo.mutex.Lock()
вместо мютекса прочитай про `SELECT FOR UPDATE SKIP LOCKED`

2022-06-04 10:35 UTC, Bazys requested changes
пара замечаний

2022-06-06 10:48 UTC, devkekops commented on internal/app/handlers/handlers.go
> +		json.NewEncoder(&buf).Encode(balance)
поменял на json.Marshal

2022-06-06 10:56 UTC, devkekops commented on internal/app/client/client.go
> +	//fmt.Println(res.StatusCode)
подчистил

2022-06-06 11:59 UTC, devkekops commented on internal/app/storage/repo_db.go
> +	mutex  sync.RWMutex
сделал

2022-06-06 12:09 UTC, devkekops commented on internal/app/storage/storage.go
> +type Order struct {
вынес в отдельный пакет

2022-06-06 12:32 UTC, devkekops commented on internal/app/client/client.go
> +type Client struct {
хорошая идея, спасибо, подправил

2022-06-06 12:55 UTC, devkekops commented on internal/app/handlers/auth_middleware.go
> +	if len(session) < 33 {
я формирую куку как id пользователя + hmac_sha256(id, secret), соответственно если передана кука с длиной 32 или меньше - возвращаю ошибку. вынес в константы, остальные вещи по auth.middleware пофиксил

2022-06-06 13:19 UTC, devkekops commented on internal/app/handlers/handlers.go
> +		userIDctx := req.Context().Value(userIDKey)
вынес

2022-06-06 13:19 UTC, devkekops commented on internal/app/handlers/handlers.go
> +		userID := userIDctx.(string)
поправил

2022-06-06 13:20 UTC, devkekops commented on internal/app/handlers/basehandler.go
> +	*chi.Mux
переделал на приватный

2022-06-06 13:58 UTC, devkekops commented on cmd/gophermart/main.go
> +		SecretKey:            "asdhkhk1375jwh132",
Да, я понимаю, просто это была строка для тестовых нужд, подчистил, генерю если не считывается

2022-06-06 18:33 UTC, devkekops commented on cmd/gophermart/main.go
> +	log.Fatal(server.Serve(&cfg))
поменял на zerolog

2022-06-06 18:36 UTC, devkekops commented
> пара замечаний

вроде бы всё пофиксил

2022-06-06 19:21 UTC, Bazys approved these changes

2022-06-07 14:00 UTC, merged